### ISSUE TITLE
Latest official release 1.0.2 injects javascript in user facing frontend 

### ISSUE THREAD

**Issue by swey** [frontend-services/craft-timetraveler#2]
The latest official version 1.0.2 is faulty because it registers an asset bundle, which should be limited to the control panel (`if if (Craft::$app->getRequest()->isCpRequest) ...`. This injects several javascript files to websites and users have to load unnecessary files.

This problem will be deprecated with 1.0.3 (https://github.com/frontend-services/craft-timetraveler/commit/50300e977e6fe2e71694ed51a6eab8c581d5abb8#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed), but this version is not officially released yet: https://packagist.org/packages/matotominac/time-traveler

**Comment by MatoTominac** [comment]
Version v1.0.4 is now live with this issue removed.
